### ISSUE TITLE
Not working for NordVPN

### ISSUE THREAD

**Issue by sojjwr** [m417z/Textify#27]
Just download the setup and try it.
https://downloads.nordcdn.com/apps/windows/NordVPN/latest/NordVPNSetup.exe

**Comment by m417z** [comment]
Textify support most, but not all apps. It relies on UI Automation, and if NordVPN doesn't implement it, e.g. if the interface is custom made and they didn't bother implementing it, then it won't work. Just like Textify doesn't work with images since there's nowhere to grab text from, and Textify doesn't do OCR.

There’s a tool from Microsoft called Inspect which shows automation-related information. It can be downloaded [here](https://www.dropbox.com/s/5cfa754k000zt07/inspect.exe?dl=1). You can try it with NordVPN to make sure it's not just an issue with Textify. Let me know if you think it is.

Similar issue about Telegram: https://github.com/m417z/Textify/issues/6

**Comment by sojjwr** [comment]
Inspect is a legacy tool. We recommend using [Accessibility Insights](https://accessibilityinsights.io/) instead.
https://learn.microsoft.com/en-us/windows/win32/winauto/inspect-objects
I tried it with Accessibility Insights and found no problems.
While installing the setup can't copy text but after running installed app sometimes it works, other times it doesn't.

**Comment by m417z** [comment]
Inspect and Accessibility Insights use the same APIs, so it shouldn't really matter. I prefer Inspect as it's more lightweight.

The setup is running as administrator (most installers are), so Textify can't grab text from it unless it's running as administrator too.  If you think there's another issue, can you post a screenshot or a video comparing Inspect (or Accessibility Insights) with Textify?
