### ISSUE TITLE
Textify don`t work

### ISSUE THREAD

**Issue by Paulchen232** [m417z/Textify#28]
I have the last version now (1.10.4) and Windows 10 22H2 and Textify don`t work.

**Comment by zhugexiaoshang** [comment]
Thank you for your letter！  I've received your letter, I'll reply to you as soon as possible.

**Comment by Paulchen232** [comment]
But the dialog works.

**Comment by Paulchen232** [comment]
I switched various things in the dialog. Now it works, only in CPU-Z (Gigabyte version) it not work.

**Comment by Paulchen232** [comment]
CPU-Z: but wie can save Report in **Tools**.

**Comment by m417z** [comment]
Textify support most, but not all apps. It relies on UI Automation, and if your program doesn't implement it, e.g. if the interface is custom made and the author didn't bother implementing it, then it won't work. Just like Textify doesn't work with images since there's nowhere to grab text from, and Textify doesn't do OCR.

There’s a tool from Microsoft called Inspect which shows automation-related information. It can be downloaded [here](https://www.dropbox.com/s/5cfa754k000zt07/inspect.exe?dl=1). You can try it with your programs to make sure it's not just an issue with Textify. Let me know if you think it is.

**Comment by Paulchen232** [comment]
Thank for your work. Now is work sufficient.
