### ISSUE TITLE
Cant reconize japanese text

### ISSUE THREAD

**Issue by CommicKick69ing** [m417z/Textify#3]
.

**Comment by m417z** [comment]
Textify should support any language, so I believe that the issue is the target program, not the language.

You can see that Textify can get Japanese text correctly e.g. from Notepad:
![Japanese with Textify](https://i.imgur.com/DY4X4pU.png)

Textify relies on UI Automation. There’s a tool from Microsoft called Inspect which shows automation-related information. It can be downloaded [here](https://www.dropbox.com/s/5cfa754k000zt07/inspect.exe?dl=1).

Please try it on the programs which Textify can’t handle, and let me know whether Inspect is able to extract the text.
